/*
 * This source file was generated by the Gradle 'init' task
 */

#ifndef APP_H
#define APP_H

#include <string>

namespace xaviers_school {
    class Greeter {
        public:
        std::string greeting();
    };
}

#endif
