/*
 * This source file was generated by the Gradle 'init' task
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"
#include "DoublyLinkedList.h"
#include "PaymentTransaction.h"

std::string xaviers_school::Greeter::greeting() {
    return std::string("Hello, Big World!");
}

int main () {
    xaviers_school::Greeter greeter;
    std::cout << greeter.greeting() << std::endl;

    DoublyLinkedList<PaymentTransaction> transactions;

    transactions.addFront(PaymentTransaction(1, 100.0, "Payment 1"));
    transactions.addFront(PaymentTransaction(0, 50.0, "Payment 0"));
    transactions.addBack(PaymentTransaction(2, 200.0, "Payment 2"));
    transactions.addBack(PaymentTransaction(3, 300.0, "Payment 3"));

    std::cout << "Transactions in forward order:" << std::endl;
    transactions.printForward();

    std::cout << "\nTransactions in backward order:" << std::endl;
    transactions.printBackward();

    return 0;
}
