/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample C++ project to get you started.
 * For more details on building C++ applications and libraries, please refer to https://docs.gradle.org/8.8/userguide/building_cpp_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the cpp-application plugin to add support for building C++ executables
    `cpp-application`

    // Apply the cpp-unit-test plugin to add support for building and running C++ test executables
    `cpp-unit-test`
}

// Set the target operating system and architecture for this application
application {
    targetMachines.add(machines.macOS.x86_64)
    targetMachines.add(machines.linux.x86_64)
    targetMachines.add(machines.windows.x86_64)
}

tasks.register<Exec>("runMain") {
    dependsOn(tasks.named("assemble"))
    group = "application"
    description = "Runs the main application"
    commandLine(file("${layout.buildDirectory.get().asFile}/exe/main/debug/vincent").absolutePath)
}

tasks.register<Exec>("runTests") {
    dependsOn(tasks.named("assemble"))
    group = "verification"
    description = "Runs the tests"
    commandLine(file("${layout.buildDirectory.get().asFile}/exe/main/debug/vincent").absolutePath, "test")
}
